<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TrimMode>partial</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/OfficeAgent.Word/OfficeAgent.Word.csproj" />
  </ItemGroup>

</Project>
