using System.Reflection;
using System.Text;
using OfficeAgent.Abstractions;
using OfficeAgent.AgentFramework;
using OfficeAgent.Core;
using OfficeAgent.Excel;
using OfficeAgent.PowerPoint;
using OfficeAgent.Rendering;
using OfficeAgent.SharePoint;
using OfficeAgent.Word;

var check = args.Length == 2 && args[0] == "--check";
var outputArgument = check ? args[1] : args.Length == 1 ? args[0] : null;
if (outputArgument is null)
{
    Console.Error.WriteLine("Usage: OfficeAgent.ApiDocs [--check] <output.md>");
    return 2;
}

var output = Path.GetFullPath(outputArgument);
var content = Generate();
if (check)
{
    if (!File.Exists(output) || File.ReadAllText(output) != content)
    {
        Console.Error.WriteLine($"Generated API reference is stale: {output}");
        return 1;
    }
    Console.WriteLine($"Generated API reference is current: {output}");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(output)!);
File.WriteAllText(output, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Generated API reference: {output}");
return 0;

static string Generate()
{
    var assemblies = new[]
    {
        typeof(DocumentPlan).Assembly,
        typeof(OfficeAgentTools).Assembly,
        typeof(OfficeAgentClient).Assembly,
        typeof(ExcelModule).Assembly,
        typeof(PowerPointModule).Assembly,
        typeof(LibreOfficeDocumentRenderer).Assembly,
        typeof(SharePointDocumentProvider).Assembly,
        typeof(WordModule).Assembly,
    }.Distinct().OrderBy(assembly => assembly.GetName().Name, StringComparer.Ordinal);

    var builder = new StringBuilder();
    var assemblyVersion = typeof(DocumentPlan).Assembly.GetName().Version
        ?? throw new InvalidOperationException("OfficeAgent.Abstractions has no assembly version");
    var version = $"{assemblyVersion.Major}.{assemblyVersion.Minor}.{assemblyVersion.Build}";
    builder.AppendLine("<!-- Generated by tools/OfficeAgent.ApiDocs. Do not edit by hand. -->");
    builder.AppendLine("# C# API reference");
    builder.AppendLine();
    builder.AppendLine($"This reference lists the public types and members in the OfficeAgent.NET library packages for v{version}. Regenerate it with:");
    builder.AppendLine();
    builder.AppendLine("```bash");
    builder.AppendLine("dotnet run --project tools/OfficeAgent.ApiDocs -- docs/csharp-api.md");
    builder.AppendLine("```");

    foreach (var assembly in assemblies)
    {
        builder.AppendLine();
        builder.AppendLine($"## {assembly.GetName().Name}");
        var types = assembly.ExportedTypes
            .Where(type => type.Namespace?.StartsWith("OfficeAgent", StringComparison.Ordinal) == true)
            .OrderBy(type => type.FullName, StringComparer.Ordinal);
        foreach (var type in types)
        {
            builder.AppendLine();
            builder.AppendLine($"### `{DisplayType(type, includeNamespace: true)}`");
            builder.AppendLine();
            builder.AppendLine("```csharp");
            builder.AppendLine(TypeDeclaration(type));

            if (type.IsEnum)
            {
                foreach (var name in Enum.GetNames(type))
                    builder.AppendLine($"{name}");
            }
            else
            {
                foreach (var member in PublicMembers(type))
                    builder.AppendLine(member);
            }
            builder.AppendLine("```");
        }
    }
    return builder.ToString().Replace("\r\n", "\n");
}

static IEnumerable<string> PublicMembers(Type type)
{
    const BindingFlags flags = BindingFlags.Public | BindingFlags.Instance |
                               BindingFlags.Static | BindingFlags.DeclaredOnly;
    foreach (var constructor in type.GetConstructors(flags).OrderBy(Signature, StringComparer.Ordinal))
        yield return Signature(constructor);
    foreach (var field in type.GetFields(flags).Where(field => !field.IsSpecialName)
                 .OrderBy(field => field.Name, StringComparer.Ordinal))
        yield return $"public {(field.IsStatic ? "static " : "")}{DisplayType(field.FieldType)} {field.Name};";
    foreach (var property in type.GetProperties(flags).OrderBy(property => property.Name, StringComparer.Ordinal))
    {
        var accessors = new[] { property.GetMethod is not null ? "get;" : null,
                              property.SetMethod is not null ? "set;" : null }
            .Where(value => value is not null);
        yield return $"public {(IsStatic(property) ? "static " : "")}{DisplayType(property.PropertyType)} {property.Name} {{ {string.Join(" ", accessors)} }}";
    }
    foreach (var method in type.GetMethods(flags).Where(method => !method.IsSpecialName)
                 .OrderBy(Signature, StringComparer.Ordinal))
        yield return Signature(method);
    foreach (var eventInfo in type.GetEvents(flags).OrderBy(eventInfo => eventInfo.Name, StringComparer.Ordinal))
        yield return $"public event {DisplayType(eventInfo.EventHandlerType!)} {eventInfo.Name};";
}

static bool IsStatic(PropertyInfo property) =>
    (property.GetMethod ?? property.SetMethod)?.IsStatic == true;

static string Signature(MethodBase method)
{
    var name = method.IsConstructor ? method.DeclaringType!.Name.Split('`')[0] : method.Name;
    if (method is MethodInfo info && info.IsGenericMethodDefinition)
        name += $"<{string.Join(", ", info.GetGenericArguments().Select(argument => argument.Name))}>";
    var parameters = string.Join(", ", method.GetParameters().Select(parameter =>
        $"{(parameter.IsOut ? "out " : parameter.ParameterType.IsByRef ? "ref " : "")}{DisplayType(parameter.ParameterType)} {parameter.Name}"));
    var modifiers = method.IsStatic ? "static " : "";
    var returnType = method is MethodInfo methodInfo ? DisplayType(methodInfo.ReturnType) + " " : "";
    return $"public {modifiers}{returnType}{name}({parameters});";
}

static string TypeDeclaration(Type type)
{
    var kind = type.IsInterface ? "interface" : type.IsEnum ? "enum" :
        typeof(MulticastDelegate).IsAssignableFrom(type.BaseType) ? "delegate" :
        type.IsValueType ? "struct" : type.IsAbstract && type.IsSealed ? "static class" :
        type.IsAbstract ? "abstract class" : type.IsSealed ? "sealed class" : "class";
    return $"public {kind} {DisplayType(type)}";
}

static string DisplayType(Type type, bool includeNamespace = false)
{
    if (type.IsByRef)
        type = type.GetElementType()!;
    if (type.IsArray)
        return $"{DisplayType(type.GetElementType()!, includeNamespace)}[]";
    if (type.IsGenericParameter)
        return type.Name;
    var nullable = Nullable.GetUnderlyingType(type);
    if (nullable is not null)
        return $"{DisplayType(nullable, includeNamespace)}?";
    var aliases = new Dictionary<Type, string>
    {
        [typeof(void)] = "void", [typeof(bool)] = "bool", [typeof(byte)] = "byte",
        [typeof(int)] = "int", [typeof(long)] = "long", [typeof(double)] = "double",
        [typeof(decimal)] = "decimal", [typeof(string)] = "string", [typeof(object)] = "object",
    };
    if (aliases.TryGetValue(type, out var alias))
        return alias;
    var prefix = includeNamespace && !string.IsNullOrEmpty(type.Namespace) ? type.Namespace + "." : "";
    var name = type.Name.Split('`')[0];
    return type.IsGenericType
        ? $"{prefix}{name}<{string.Join(", ", type.GetGenericArguments().Select(argument => DisplayType(argument, includeNamespace)))}>"
        : prefix + name;
}
