using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using OfficeAgent.Abstractions;
using OfficeAgent.AgentFramework;
using OfficeAgent.Core;
using OfficeAgent.Core.DocumentProviders;
using OfficeAgent.Excel;
using OfficeAgent.Mcp;
using OfficeAgent.PowerPoint;
using OfficeAgent.Word;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using W = DocumentFormat.OpenXml.Wordprocessing;

/// <summary>
/// Renders the JSON contracts an agent or host depends on, as a baseline the check compares
/// verbatim.
/// </summary>
/// <remarks>
/// <para>
/// The .NET baseline cannot see these. A verb that maps to a different operation, an anchor
/// discriminator spelled differently, or a tool parameter that becomes required changes nothing
/// in any C# signature and breaks every stored plan or scripted agent that relied on it.
/// </para>
/// <para>
/// Everything here is read from the running code, not listed by hand: the verb map is the
/// converter's own dictionary, member names come from the canonical plan serializer options,
/// anchor discriminators come from round-tripping each anchor type through its converter, and
/// tool schemas are the ones the Agent Framework and MCP surfaces actually publish. A list kept
/// by hand drifts from the code it describes; this cannot.
/// </para>
/// <para>
/// Descriptions are deliberately excluded from tool schemas. They are guidance for a model, and
/// rewording one breaks no caller; a gate that failed on every wording change would train people
/// to regenerate it without reading the diff.
/// </para>
/// </remarks>
internal static class WireContract
{
    // A copy, so the shared production instance is never made read-only by this tool. The copy
    // constructor carries the naming policy, converters and member handling unchanged; only the
    // resolver, which the production options acquire on first use, is supplied explicitly.
    private static readonly JsonSerializerOptions PlanJson = new(OfficeAgentTools.PlanJson)
    {
        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()
    };

    public static string Generate()
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!-- Generated by tools/OfficeAgent.ApiDocs. Do not edit by hand. -->");
        builder.AppendLine("# Wire contract");
        builder.AppendLine();
        builder.AppendLine("The JSON an agent or host exchanges with OfficeAgent, read from the running code. It is the");
        builder.AppendLine("compatibility baseline for everything the C# API reference cannot see. Regenerate both with:");
        builder.AppendLine();
        builder.AppendLine("```bash");
        builder.AppendLine("dotnet run --project tools/OfficeAgent.ApiDocs -- docs/csharp-api.md docs/wire-contract.md");
        builder.AppendLine("```");

        Operations(builder);
        Anchors(builder);
        Tools(builder);
        Outputs(builder);
        Configuration(builder);
        Defaults(builder);

        return builder.ToString().Replace("\r\n", "\n");
    }

    private static void Operations(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Plan operations");
        builder.AppendLine();
        builder.AppendLine("The `op` value selects the operation, case-insensitively. Members are read by these names,");
        builder.AppendLine("case-insensitively; an unknown member, verb or enum value is refused with `invalid-json`.");
        builder.AppendLine("Enum members are exchanged by name and integers are refused.");

        foreach (var (verb, type) in PlanOperationJsonConverter.ByVerb
                     .OrderBy(pair => pair.Key, StringComparer.Ordinal))
        {
            builder.AppendLine();
            builder.AppendLine($"### `{verb}`");
            builder.AppendLine();
            builder.AppendLine($"Type: `{type.FullName}`");
            builder.AppendLine();
            builder.AppendLine("```text");
            foreach (var member in Members(type))
                builder.AppendLine(member);
            builder.AppendLine("```");
        }
    }

    private static void Anchors(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Anchors");
        builder.AppendLine();
        builder.AppendLine("Every anchor is written with a `$anchor` discriminator, and read with one when it is present.");

        var anchors = typeof(Anchor).Assembly.GetExportedTypes()
            .Where(type => typeof(Anchor).IsAssignableFrom(type) && !type.IsAbstract &&
                           type.GetConstructor(Type.EmptyTypes) is not null)
            .OrderBy(type => type.FullName, StringComparer.Ordinal);

        foreach (var type in anchors)
        {
            var instance = (Anchor)Activator.CreateInstance(type)!;
            var written = JsonNode.Parse(JsonSerializer.Serialize(instance, typeof(Anchor), PlanJson))!;
            var discriminator = written["$anchor"]?.GetValue<string>() ?? "(none)";

            builder.AppendLine();
            builder.AppendLine($"### `$anchor: {discriminator}`");
            builder.AppendLine();
            builder.AppendLine($"Type: `{type.FullName}`");
            builder.AppendLine();
            builder.AppendLine("```text");
            foreach (var member in Members(type))
                builder.AppendLine(member);
            builder.AppendLine("```");
        }
    }

    private static void Tools(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Tools");
        builder.AppendLine();
        builder.AppendLine("Every tool the Agent Framework surface can publish, with every opt-in enabled. The MCP server");
        builder.AppendLine("publishes the same functions. Parameter schemas are shown without descriptions.");

        var client = new OfficeAgentClient(new WordModule(), new PowerPointModule(), new ExcelModule());
        var functions = new OfficeAgentTools(client).AsAIFunctions(new OfficeAgentToolsOptions
        {
            AllowRegistration = true,
            AllowCreation = true,
            AllowInlineContent = true,
            AllowConnectionAddressing = true,
            AllowEphemeralDocuments = true
        });

        foreach (var function in functions.OrderBy(function => function.Name, StringComparer.Ordinal))
        {
            var schema = Canonical(JsonNode.Parse(function.JsonSchema.GetRawText()));
            builder.AppendLine();
            builder.AppendLine($"### `{function.Name}`");
            builder.AppendLine();
            builder.AppendLine("```json");
            builder.AppendLine(schema?.ToJsonString(new JsonSerializerOptions { WriteIndented = true })
                .Replace("\r\n", "\n") ?? "null");
            builder.AppendLine("```");
        }
    }


    /// <summary>
    /// The shape of what representative tools return, as property paths and value kinds.
    /// </summary>
    /// <remarks>
    /// Inputs are not the whole contract. A host that reads a response depends on the fields in
    /// it, and responses the adapter builds from anonymous objects appear in no C# signature, so
    /// removing <c>paraId</c> from a find hit, or <c>code</c> from an error entry, would otherwise
    /// pass every gate. Values are excluded because identifiers, hashes and timestamps vary
    /// between runs; paths and kinds do not, given the same fixture. Array elements are merged
    /// under <c>[]</c>, so a path records every shape an element of that array took.
    /// </remarks>
    private static void Configuration(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Configuration");
        builder.AppendLine();
        builder.AppendLine($"The MCP server binds the `{OfficeAgentMcpOptions.SectionName}` section. A configuration file is named by");
        builder.AppendLine($"`{OfficeAgentConfiguration.PathOption}` or the `{OfficeAgentConfiguration.PathVariable}` environment variable. Keys, their types and");
        builder.AppendLine("their defaults as constructed; `[]` marks a list whose elements take the keys beneath it.");
        builder.AppendLine();
        builder.AppendLine("```text");
        foreach (var line in ConfigurationKeys(typeof(OfficeAgentMcpOptions), OfficeAgentMcpOptions.SectionName, Activator.CreateInstance(typeof(OfficeAgentMcpOptions))))
            builder.AppendLine(line);
        builder.AppendLine("```");
    }

    private static IEnumerable<string> ConfigurationKeys(Type type, string prefix, object? instance)
    {
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                     .Where(property => property.SetMethod?.IsPublic == true)
                     .OrderBy(property => property.Name, StringComparer.Ordinal))
        {
            var key = $"{prefix}:{property.Name}";
            var element = ListElement(property.PropertyType);
            if (element is not null && IsSettings(element))
            {
                foreach (var line in ConfigurationKeys(element, key + "[]", Activator.CreateInstance(element)))
                    yield return line;
                continue;
            }
            var value = instance is null ? null : property.GetValue(instance);
            yield return $"{key}: {TypeName(property.PropertyType)} = {Literal(value)}";
        }
    }

    private static void Defaults(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Defaults");
        builder.AppendLine();
        builder.AppendLine("What a member holds when a caller does not set it, for every public type a caller constructs:");
        builder.AppendLine("options, limits, requests and plan operations. Enum values are always listed; other values");
        builder.AppendLine("only when they differ from the CLR default (`null`, `0`, `false`), so a default that changes,");
        builder.AppendLine("appears or disappears is a line in the diff. Tracked-versus-direct defaults and every ceiling");
        builder.AppendLine("live here.");

        var types = ApiSurface.Shipped
            .SelectMany(assembly => assembly.ExportedTypes)
            .Where(type => type.IsClass && !type.IsAbstract && !type.IsGenericTypeDefinition &&
                           type.Namespace?.StartsWith("OfficeAgent", StringComparison.Ordinal) == true &&
                           !typeof(Exception).IsAssignableFrom(type) &&
                           !typeof(IDisposable).IsAssignableFrom(type) &&
                           type.GetConstructor(Type.EmptyTypes) is not null &&
                           !type.GetCustomAttributesData().Any(attribute =>
                               attribute.AttributeType.FullName == "System.Diagnostics.CodeAnalysis.ExperimentalAttribute"))
            .OrderBy(type => type.FullName, StringComparer.Ordinal);

        foreach (var type in types)
        {
            var lines = DefaultValues(type, "", Activator.CreateInstance(type)!, depth: 0).ToList();
            if (lines.Count == 0) continue;
            builder.AppendLine();
            builder.AppendLine($"### `{type.FullName}`");
            builder.AppendLine();
            builder.AppendLine("```text");
            foreach (var line in lines)
                builder.AppendLine(line);
            builder.AppendLine("```");
        }
    }

    private static IEnumerable<string> DefaultValues(Type type, string prefix, object instance, int depth)
    {
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                     .Where(property => property.GetMethod?.IsPublic == true && property.SetMethod?.IsPublic == true &&
                                        property.GetIndexParameters().Length == 0)
                     .OrderBy(property => property.Name, StringComparer.Ordinal))
        {
            var value = property.GetValue(instance);
            var name = prefix + property.Name;
            if (value is null) continue;
            var valueType = value.GetType();
            // An enum's zero is a named choice, not an absence: Tracked is ChangeMode 0, and the
            // tracked default is the one this section most needs to show.
            if (valueType.IsValueType && !valueType.IsEnum && value.Equals(Activator.CreateInstance(valueType))) continue;
            // A nested settings object is described member by member, so a changed ceiling
            // inside it is one line rather than a whole reserialized object.
            if (IsSettings(valueType) && depth < 4)
            {
                foreach (var line in DefaultValues(valueType, name + ".", value, depth + 1))
                    yield return line;
                continue;
            }
            yield return $"{name} = {Literal(value)}";
        }
    }

    /// <summary>An OfficeAgent class described by its members rather than as one value.</summary>
    private static bool IsSettings(Type type) =>
        type.IsClass && type != typeof(string) &&
        type.Namespace?.StartsWith("OfficeAgent", StringComparison.Ordinal) == true &&
        type.GetConstructor(Type.EmptyTypes) is not null;

    private static Type? ListElement(Type type)
    {
        if (type.IsArray) return type.GetElementType();
        if (type == typeof(string)) return null;
        return type.GetInterfaces().Concat(type.IsInterface ? new[] { type } : Array.Empty<Type>())
            .FirstOrDefault(candidate => candidate.IsGenericType &&
                                         candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            ?.GetGenericArguments()[0];
    }

    private static readonly JsonSerializerOptions LiteralJson = new()
    {
        Converters = { new System.Text.Json.Serialization.JsonStringEnumConverter() },
        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()
    };

    private static string Literal(object? value) => value switch
    {
        null => "null",
        string text => JsonSerializer.Serialize(text),
        bool flag => flag ? "true" : "false",
        Enum member => member.ToString(),
        TimeSpan span => span.ToString("c", CultureInfo.InvariantCulture),
        IFormattable number => number.ToString(null, CultureInfo.InvariantCulture),
        _ => JsonSerializer.Serialize(value, value.GetType(), LiteralJson)
    };

    private static void Outputs(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Tool responses");
        builder.AppendLine();
        builder.AppendLine("The structure of representative responses, produced by calling each tool against a document");
        builder.AppendLine("built in memory for the purpose. Each line is a property path and the JSON kinds seen there.");
        builder.AppendLine("Values are omitted because identifiers, hashes and timestamps vary between runs.");

        foreach (var (name, json) in RepresentativeResponses().GetAwaiter().GetResult())
        {
            var shape = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
            Shape(JsonNode.Parse(json), "$", shape);
            builder.AppendLine();
            builder.AppendLine($"### {name}");
            builder.AppendLine();
            builder.AppendLine("```text");
            foreach (var (path, kinds) in shape)
                builder.AppendLine($"{path}: {string.Join(" | ", kinds)}");
            builder.AppendLine("```");
        }
    }

    private static async Task<IReadOnlyList<(string Name, string Json)>> RepresentativeResponses()
    {
        // Path-addressed tools (register, open, edit) need a provider over real paths, so a
        // throwaway folder backs a second connection. Every other tool runs in memory.
        var folder = Path.Combine(Path.GetTempPath(), $"officeagent-wire-{Guid.NewGuid():N}");
        Directory.CreateDirectory(folder);
        try
        {
            return await RepresentativeResponses(folder);
        }
        finally
        {
            Directory.Delete(folder, recursive: true);
        }
    }

    private static async Task<IReadOnlyList<(string Name, string Json)>> RepresentativeResponses(string folder)
    {
        var memory = new MemoryDocumentProvider("memory");
        var workspace = new FileSystemDocumentProvider(new FileSystemDocumentProviderOptions
        {
            ConnectionId = "workspace",
            RootPath = folder
        });
        var client = new OfficeAgentClient(
            new DocumentProviderRegistry(new IDocumentProvider[] { memory, workspace }),
            new WordModule(), new PowerPointModule(), new ExcelModule());
        var tools = new OfficeAgentTools(client);

        var createPlan = "{\"operations\":[{\"op\":\"changeText\",\"target\":{\"paraId\":\"auto-0000\",\"expect\":\"\"}," +
                         "\"with\":\"Prepared for Northwind Labs.\"}]}";
        var created = await tools.CreateDocument("memory", "fixture.docx", createPlan);
        var documentId = Field(JsonNode.Parse(created)!, "outputDocumentId").GetValue<string>();
        // Merge refuses pending revisions, and a created document is tracked by default, so the
        // merge sources are written directly.
        var directPlan = createPlan.Replace("\"with\":", "\"mode\":\"Direct\",\"with\":");
        var mergeLeft = Field(JsonNode.Parse(await tools.CreateDocument("memory", "left.docx", directPlan))!,
            "outputDocumentId").GetValue<string>();
        var second = Field(JsonNode.Parse(await tools.CreateDocument("memory", "second.docx", directPlan))!,
            "outputDocumentId").GetValue<string>();

        // The fixture reads responses case-insensitively, so the generator can describe any
        // release, including 0.9, whose inspect records were PascalCase.
        var inspect = await tools.InspectDocument("memory", documentId);
        var editPlan = EditPlanFor(inspect);

        var exported = await tools.ExportDocumentContent("memory", documentId);
        var content = Field(JsonNode.Parse(exported)!, "contentBase64").GetValue<string>();
        File.WriteAllBytes(Path.Combine(folder, "fixture.docx"), Convert.FromBase64String(content));
        var registered = await tools.RegisterDocument("workspace", "fixture.docx");
        var opened = await tools.OpenDocument("workspace", "fixture.docx");
        var inlineCreated = await tools.CreateDocumentContent("inline.docx", createPlan);
        var inlineContent = Field(JsonNode.Parse(inlineCreated)!, "contentBase64").GetValue<string>();
        var inlineInspect = await tools.InspectDocumentContent(inlineContent);

        var imported = await tools.ImportDocumentContent("memory", "quote.docx",
            Convert.ToBase64String(QuoteTemplate()));
        var templateId = Field(JsonNode.Parse(imported)!, "documentId").GetValue<string>();
        const string batch = "{\"items\":[{\"outputName\":\"quote-a.docx\",\"binding\":{" +
                             "\"values\":{\"CustomerName\":\"Fabrikam\"},\"missingValueBehavior\":\"Ignore\"}}]}";
        var batchPreview = await tools.PreviewTemplateBatch("memory", templateId, batch);
        var token = Field(JsonNode.Parse(batchPreview)!, "token").ToJsonString();

        var mergePreview = await tools.PreviewDocumentMerge(
            "{\"sources\":[{\"connectionId\":\"memory\",\"documentId\":\"" + mergeLeft + "\"}," +
            "{\"connectionId\":\"memory\",\"documentId\":\"" + second + "\"}]}");
        var mergePlan = Field(JsonNode.Parse(mergePreview)!, "plan").ToJsonString();

        return new List<(string, string)>
        {
            ("`describe_capabilities`", await tools.DescribeCapabilities()),
            ("`create_document`", created),
            ("`inspect_document`", inspect),
            ("`find_in_document`", await tools.FindInDocument("memory", documentId, "Northwind")),
            ("`preview_plan`", await tools.PreviewPlan("memory", documentId, editPlan)),
            ("`compare_documents`", await tools.CompareDocuments("memory", documentId, "memory", documentId)),
            ("`apply_plan`", await tools.ApplyPlan("memory", documentId, editPlan)),
            ("`export_document_content`", exported),
            ("`import_document_content`", imported),
            ("`register_document`", registered),
            ("`open_document`", opened),
            ("`edit_document`", await tools.EditDocument("workspace", "fixture.docx", EditPlanFor(opened))),
            ("`create_document_content`", inlineCreated),
            ("`inspect_document_content`", inlineInspect),
            ("`edit_document_content`", await tools.EditDocumentContent(inlineContent, EditPlanFor(inlineInspect))),
            ("`discover_template`", await tools.DiscoverTemplate("memory", templateId)),
            ("`preview_template_batch`", batchPreview),
            ("`populate_template_batch`", await tools.PopulateTemplateBatch("memory", templateId, batch, token)),
            ("`preview_document_merge`", mergePreview),
            ("`merge_documents`", await tools.MergeDocuments(mergePlan, "memory", "packet.docx")),
            ("`remove_document`", await tools.RemoveDocument("memory", second)),
            ("Error envelope: unreadable plan JSON", await tools.PreviewPlan("memory", documentId, "{\"bogus\":1}")),
            ("Error envelope: unknown document", await tools.ApplyPlan("memory", "no-such-document", editPlan)),
        };
    }

    /// <summary>A one-operation plan that edits the first non-empty paragraph an inspection reported.</summary>
    private static string EditPlanFor(string inspection)
    {
        var root = JsonNode.Parse(inspection)!;
        // Some tools nest the inspection in a wrapper; inspect_document returns it at the root.
        var inspected = root.AsObject().Any(pair => string.Equals(pair.Key, "paragraphs", StringComparison.OrdinalIgnoreCase))
            ? root
            : Field(root, "inspection");
        var paragraph = Field(inspected, "paragraphs").AsArray()
            .First(item => (Field(item!, "text").GetValue<string>() ?? "").Length > 0)!;
        return "{\"operations\":[{\"op\":\"changeText\",\"target\":{\"paraId\":\"" +
               Field(paragraph, "paraId").GetValue<string>() + "\",\"expect\":\"" +
               Field(paragraph, "text").GetValue<string>() + "\"},\"with\":\"Revised for Contoso.\"}]}";
    }

    /// <summary>A template with one content-control slot and one repeating table row.</summary>
    private static byte[] QuoteTemplate()
    {
        static W.TableRow Row(params string[] values) => new(values.Select(value =>
            new W.TableCell(new W.Paragraph(new W.Run(new W.Text(value))))));

        using var stream = new MemoryStream();
        using (var document = WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document))
        {
            var main = document.AddMainDocumentPart();
            main.Document = new W.Document(new W.Body(
                new W.Paragraph(
                    new W.Run(new W.Text("Quote for ")),
                    new W.SdtRun(
                        new W.SdtProperties(new W.Tag { Val = "CustomerName" }, new W.SdtId { Val = 11 }),
                        new W.SdtContentRun(new W.Run(new W.Text("CUSTOMER"))))),
                new W.Table(
                    new W.TableGrid(new W.GridColumn { Width = "3600" }, new W.GridColumn { Width = "1200" }),
                    Row("Description", "Quantity"),
                    Row("{{Description}}", "{{Quantity}}")),
                new W.Paragraph()));
            main.Document.Save();
        }
        return stream.ToArray();
    }

    /// <summary>
    /// Reads one fixture field. A missing field means a fixture call failed, so the response is
    /// reported rather than surfacing later as a null reference far from its cause.
    /// </summary>
    private static JsonNode Field(JsonNode node, string name) =>
        node.AsObject().FirstOrDefault(pair => string.Equals(pair.Key, name, StringComparison.OrdinalIgnoreCase)).Value
        ?? throw new InvalidOperationException($"Fixture response has no '{name}': {node.ToJsonString()}");

    private static void Shape(JsonNode? node, string path, SortedDictionary<string, SortedSet<string>> shape)
    {
        void Record(string kind)
        {
            if (!shape.TryGetValue(path, out var kinds))
                shape[path] = kinds = new SortedSet<string>(StringComparer.Ordinal);
            kinds.Add(kind);
        }

        switch (node)
        {
            case null:
                Record("null");
                break;
            case JsonObject obj:
                Record("object");
                foreach (var (key, value) in obj)
                    Shape(value, $"{path}.{key}", shape);
                break;
            case JsonArray array:
                Record("array");
                foreach (var item in array)
                    Shape(item, $"{path}[]", shape);
                break;
            case JsonValue value:
                Record(value.GetValueKind() switch
                {
                    JsonValueKind.String => "string",
                    JsonValueKind.Number => "number",
                    JsonValueKind.True or JsonValueKind.False => "boolean",
                    _ => "null"
                });
                break;
        }
    }

    /// <summary>The JSON members of a type as the canonical plan options read and write them.</summary>
    private static IEnumerable<string> Members(Type type)
    {
        var info = PlanJson.GetTypeInfo(type);
        return info.Properties
            .Select(property => $"{property.Name}: {TypeName(property.PropertyType)}" +
                                (property.IsRequired ? " (required)" : ""))
            .OrderBy(text => text, StringComparer.Ordinal);
    }

    private static string TypeName(Type type)
    {
        var nullable = Nullable.GetUnderlyingType(type);
        if (nullable is not null) return TypeName(nullable) + "?";
        if (type.IsArray) return TypeName(type.GetElementType()!) + "[]";
        if (!type.IsGenericType) return type.Name;
        var name = type.Name.Split('`')[0];
        return $"{name}<{string.Join(", ", type.GetGenericArguments().Select(TypeName))}>";
    }

    /// <summary>Sorted keys, descriptions removed, so the text changes only when the contract does.</summary>
    private static JsonNode? Canonical(JsonNode? node)
    {
        switch (node)
        {
            case JsonObject obj:
                var sorted = new JsonObject();
                foreach (var pair in obj.OrderBy(pair => pair.Key, StringComparer.Ordinal))
                {
                    if (pair.Key is "description" or "title") continue;
                    sorted[pair.Key] = Canonical(pair.Value?.DeepClone());
                }
                return sorted;
            case JsonArray array:
                var copy = new JsonArray();
                foreach (var item in array) copy.Add(Canonical(item?.DeepClone()));
                return copy;
            default:
                return node?.DeepClone();
        }
    }
}
