using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.Extensions.AI;
using OfficeAgent.Abstractions;
using OfficeAgent.AgentFramework;
using OfficeAgent.Core;
using OfficeAgent.Core.DocumentProviders;
using OfficeAgent.Excel;
using OfficeAgent.Mcp;
using OfficeAgent.PowerPoint;
using OfficeAgent.Word;

/// <summary>
/// Renders the JSON contracts an agent or host depends on, as a baseline the check compares
/// verbatim.
/// </summary>
/// <remarks>
/// <para>
/// The .NET baseline cannot see these. A verb that maps to a different operation, an anchor
/// discriminator spelled differently, or a tool parameter that becomes required changes nothing
/// in any C# signature and breaks every stored plan or scripted agent that relied on it.
/// </para>
/// <para>
/// Everything here is read from the running code, not listed by hand: the verb map is the
/// converter's own dictionary, member names come from the canonical plan serializer options,
/// anchor discriminators come from round-tripping each anchor type through its converter, and
/// tool schemas are the ones the Agent Framework and MCP surfaces actually publish. A list kept
/// by hand drifts from the code it describes; this cannot.
/// </para>
/// <para>
/// Descriptions are deliberately excluded from tool schemas. They are guidance for a model, and
/// rewording one breaks no caller; a gate that failed on every wording change would train people
/// to regenerate it without reading the diff.
/// </para>
/// </remarks>
internal static class WireContract
{
    // A copy, so the shared production instance is never made read-only by this tool. The copy
    // constructor carries the naming policy, converters and member handling unchanged; only the
    // resolver, which the production options acquire on first use, is supplied explicitly.
    private static readonly JsonSerializerOptions PlanJson = new(OfficeAgentTools.PlanJson)
    {
        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()
    };

    public static string Generate()
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!-- Generated by tools/OfficeAgent.ApiDocs. Do not edit by hand. -->");
        builder.AppendLine("# Wire contract");
        builder.AppendLine();
        builder.AppendLine("The JSON an agent or host exchanges with OfficeAgent, read from the running code. It is the");
        builder.AppendLine("compatibility baseline for everything the C# API reference cannot see. Regenerate both with:");
        builder.AppendLine();
        builder.AppendLine("```bash");
        builder.AppendLine("dotnet run --project tools/OfficeAgent.ApiDocs -- docs/csharp-api.md docs/wire-contract.md");
        builder.AppendLine("```");

        Operations(builder);
        Anchors(builder);
        Tools(builder);
        Outputs(builder);
        Configuration(builder);
        Defaults(builder);

        return builder.ToString().Replace("\r\n", "\n");
    }

    private static void Operations(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Plan operations");
        builder.AppendLine();
        builder.AppendLine("The `op` value selects the operation, case-insensitively. Members are read by these names,");
        builder.AppendLine("case-insensitively; an unknown member, verb or enum value is refused with `invalid-json`.");
        builder.AppendLine("Enum members are exchanged by name and integers are refused.");

        foreach (var (verb, type) in PlanOperationJsonConverter.ByVerb
                     .OrderBy(pair => pair.Key, StringComparer.Ordinal))
        {
            builder.AppendLine();
            builder.AppendLine($"### `{verb}`");
            builder.AppendLine();
            builder.AppendLine($"Type: `{type.FullName}`");
            builder.AppendLine();
            builder.AppendLine("```text");
            foreach (var member in Members(type))
                builder.AppendLine(member);
            builder.AppendLine("```");
        }
    }

    private static void Anchors(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Anchors");
        builder.AppendLine();
        builder.AppendLine("Every anchor is written with a `$anchor` discriminator, and read with one when it is present.");

        var anchors = typeof(Anchor).Assembly.GetExportedTypes()
            .Where(type => typeof(Anchor).IsAssignableFrom(type) && !type.IsAbstract &&
                           type.GetConstructor(Type.EmptyTypes) is not null)
            .OrderBy(type => type.FullName, StringComparer.Ordinal);

        foreach (var type in anchors)
        {
            var instance = (Anchor)Activator.CreateInstance(type)!;
            var written = JsonNode.Parse(JsonSerializer.Serialize(instance, typeof(Anchor), PlanJson))!;
            var discriminator = written["$anchor"]?.GetValue<string>() ?? "(none)";

            builder.AppendLine();
            builder.AppendLine($"### `$anchor: {discriminator}`");
            builder.AppendLine();
            builder.AppendLine($"Type: `{type.FullName}`");
            builder.AppendLine();
            builder.AppendLine("```text");
            foreach (var member in Members(type))
                builder.AppendLine(member);
            builder.AppendLine("```");
        }
    }

    private static void Tools(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Tools");
        builder.AppendLine();
        builder.AppendLine("Every tool the Agent Framework surface can publish with every opt-in enabled, then the tools only");
        builder.AppendLine("the MCP server adds. Generation fails if the MCP server publishes a shared tool with a different");
        builder.AppendLine("schema. Parameter schemas are shown without descriptions.");

        var client = new OfficeAgentClient(new WordModule(), new PowerPointModule(), new ExcelModule());
        var tools = new OfficeAgentTools(client);
        var functions = tools.AsAIFunctions(new OfficeAgentToolsOptions
        {
            AllowRegistration = true,
            AllowCreation = true,
            AllowInlineContent = true,
            AllowConnectionAddressing = true,
            AllowEphemeralDocuments = true
        });
        var schemas = functions.ToDictionary(
            function => function.Name,
            function => Canonical(JsonNode.Parse(function.JsonSchema.GetRawText())),
            StringComparer.Ordinal);

        var mcp = OfficeAgentMcpServer.CreateTools(tools, new OfficeAgentMcpOptions
        {
            AllowRegistration = true,
            AllowCreation = true,
            AllowInlineContent = true,
            EphemeralConnectionId = "session",
            FileSystemConnections = { new FileSystemConnectionOptions { ConnectionId = "workspace", RootPath = Path.GetTempPath() } }
        });
        var mcpOnly = new SortedDictionary<string, JsonNode?>(StringComparer.Ordinal);
        foreach (var tool in mcp)
        {
            var schema = Canonical(JsonNode.Parse(tool.ProtocolTool.InputSchema.GetRawText()));
            if (!schemas.TryGetValue(tool.ProtocolTool.Name, out var shared))
                mcpOnly[tool.ProtocolTool.Name] = schema;
            else if (!JsonNode.DeepEquals(shared, schema))
                throw new InvalidOperationException($"The MCP server publishes {tool.ProtocolTool.Name} with a different schema.");
        }

        foreach (var (name, schema) in schemas.OrderBy(pair => pair.Key, StringComparer.Ordinal))
            AppendSchema(builder, $"`{name}`", schema);
        foreach (var (name, schema) in mcpOnly)
            AppendSchema(builder, $"`{name}` (MCP server only)", schema);
    }

    private static void AppendSchema(StringBuilder builder, string heading, JsonNode? schema)
    {
        builder.AppendLine();
        builder.AppendLine($"### {heading}");
        builder.AppendLine();
        builder.AppendLine("```json");
        builder.AppendLine(schema?.ToJsonString(new JsonSerializerOptions { WriteIndented = true })
            .Replace("\r\n", "\n") ?? "null");
        builder.AppendLine("```");
    }

    private static void Configuration(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Configuration");
        builder.AppendLine();
        builder.AppendLine($"The MCP server binds the `{OfficeAgentMcpOptions.SectionName}` section. A configuration file is named by");
        builder.AppendLine($"`{OfficeAgentConfiguration.PathOption}` or the `{OfficeAgentConfiguration.PathVariable}` environment variable. Keys, their types and");
        builder.AppendLine("their defaults as constructed; `[]` marks a list whose elements take the keys beneath it.");
        builder.AppendLine();
        builder.AppendLine("```text");
        foreach (var line in ConfigurationKeys(typeof(OfficeAgentMcpOptions), OfficeAgentMcpOptions.SectionName, Activator.CreateInstance(typeof(OfficeAgentMcpOptions))))
            builder.AppendLine(line);
        builder.AppendLine("```");
    }

    private static IEnumerable<string> ConfigurationKeys(Type type, string prefix, object? instance)
    {
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                     .Where(property => property.SetMethod?.IsPublic == true)
                     .OrderBy(property => property.Name, StringComparer.Ordinal))
        {
            var key = $"{prefix}:{property.Name}";
            var element = ListElement(property.PropertyType);
            if (element is not null && IsSettings(element))
            {
                foreach (var line in ConfigurationKeys(element, key + "[]", Activator.CreateInstance(element)))
                    yield return line;
                continue;
            }
            var value = instance is null ? null : property.GetValue(instance);
            yield return $"{key}: {TypeName(property.PropertyType)} = {Literal(value)}";
        }
    }

    private static void Defaults(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("## Defaults");
        builder.AppendLine();
        builder.AppendLine("What a member holds when a caller does not set it, for every public type a caller constructs:");
        builder.AppendLine("options, limits, requests and plan operations. Enum values are always listed; other values");
        builder.AppendLine("only when they differ from the CLR default (`null`, `0`, `false`), so a default that changes,");
        builder.AppendLine("appears or disappears is a line in the diff. Tracked-versus-direct defaults and every ceiling");
        builder.AppendLine("live here.");

        var types = ApiSurface.Shipped
            .SelectMany(assembly => assembly.ExportedTypes)
            .Where(type => type.IsClass && !type.IsAbstract && !type.IsGenericTypeDefinition &&
                           type.Namespace?.StartsWith("OfficeAgent", StringComparison.Ordinal) == true &&
                           !typeof(Exception).IsAssignableFrom(type) &&
                           !typeof(IDisposable).IsAssignableFrom(type) &&
                           type.GetConstructor(Type.EmptyTypes) is not null &&
                           !type.GetCustomAttributesData().Any(attribute =>
                               attribute.AttributeType.FullName == "System.Diagnostics.CodeAnalysis.ExperimentalAttribute"))
            .OrderBy(type => type.FullName, StringComparer.Ordinal);

        foreach (var type in types)
        {
            var lines = DefaultValues(type, "", Activator.CreateInstance(type)!, depth: 0).ToList();
            if (lines.Count == 0) continue;
            builder.AppendLine();
            builder.AppendLine($"### `{type.FullName}`");
            builder.AppendLine();
            builder.AppendLine("```text");
            foreach (var line in lines)
                builder.AppendLine(line);
            builder.AppendLine("```");
        }
    }

    private static IEnumerable<string> DefaultValues(Type type, string prefix, object instance, int depth)
    {
        foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
                     .Where(property => property.GetMethod?.IsPublic == true && property.SetMethod?.IsPublic == true &&
                                        property.GetIndexParameters().Length == 0)
                     .OrderBy(property => property.Name, StringComparer.Ordinal))
        {
            var value = property.GetValue(instance);
            var name = prefix + property.Name;
            if (value is null) continue;
            var valueType = value.GetType();
            // An enum's zero is a named choice, not an absence: Tracked is ChangeMode 0, and the
            // tracked default is the one this section most needs to show.
            if (valueType.IsValueType && !valueType.IsEnum && value.Equals(Activator.CreateInstance(valueType))) continue;
            // A nested settings object is described member by member, so a changed ceiling
            // inside it is one line rather than a whole reserialized object.
            if (IsSettings(valueType) && depth < 4)
            {
                foreach (var line in DefaultValues(valueType, name + ".", value, depth + 1))
                    yield return line;
                continue;
            }
            yield return $"{name} = {Literal(value)}";
        }
    }

    /// <summary>An OfficeAgent class described by its members rather than as one value.</summary>
    private static bool IsSettings(Type type) =>
        type.IsClass && type != typeof(string) &&
        type.Namespace?.StartsWith("OfficeAgent", StringComparison.Ordinal) == true &&
        type.GetConstructor(Type.EmptyTypes) is not null;

    private static Type? ListElement(Type type)
    {
        if (type.IsArray) return type.GetElementType();
        if (type == typeof(string)) return null;
        return type.GetInterfaces().Concat(type.IsInterface ? new[] { type } : Array.Empty<Type>())
            .FirstOrDefault(candidate => candidate.IsGenericType &&
                                         candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            ?.GetGenericArguments()[0];
    }

    private static readonly JsonSerializerOptions LiteralJson = new()
    {
        Converters = { new System.Text.Json.Serialization.JsonStringEnumConverter() },
        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()
    };

    private static string Literal(object? value) => value switch
    {
        null => "null",
        string text => JsonSerializer.Serialize(text),
        bool flag => flag ? "true" : "false",
        Enum member => member.ToString(),
        TimeSpan span => span.ToString("c", CultureInfo.InvariantCulture),
        IFormattable number => number.ToString(null, CultureInfo.InvariantCulture),
        _ => JsonSerializer.Serialize(value, value.GetType(), LiteralJson)
    };

    // Copies, for the same reason as PlanJson above.
    private static readonly JsonSerializerOptions ResponseJson = new(OfficeAgentTools.Json)
    {
        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()
    };

    private static readonly JsonSerializerOptions CapabilityJson = new(OfficeAgentTools.CapabilityJson)
    {
        TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver()
    };

    /// <summary>
    /// Tools whose success response is one typed record, and the options it is written with.
    /// Their shape is derived from the type, so it covers every member in every state; the
    /// execution states below then prove each real response stays inside that schema.
    /// </summary>
    private static readonly (string Tool, Type Type, JsonSerializerOptions Options)[] TypedResponses =
    {
        ("compare_documents", typeof(DocumentComparisonResult), PlanJson),
        ("describe_capabilities", typeof(EngineCapabilities), CapabilityJson),
        ("discover_template", typeof(TemplateDiscoveryResult), PlanJson),
        ("merge_documents", typeof(DocumentMergeResult), PlanJson),
        ("populate_template_batch", typeof(TemplateBatchResult), PlanJson),
        ("preview_document_merge", typeof(DocumentMergePreview), PlanJson),
        ("preview_template_batch", typeof(TemplateBatchPreview), PlanJson),
    };

    private static void Outputs(StringBuilder builder)
    {
        var states = ResponseStates.Generate().GetAwaiter().GetResult();

        builder.AppendLine();
        builder.AppendLine("## Tool responses");
        builder.AppendLine();
        builder.AppendLine("Responses are frozen in three layers. Each says exactly what it covers; a response state not");
        builder.AppendLine("listed under a tool is not frozen by this file.");
        builder.AppendLine();
        builder.AppendLine("1. **Typed results** are derived from the result type, so every member, its nullability and every");
        builder.AppendLine("   enum value are covered whatever state produced the response.");
        builder.AppendLine("2. **Shared parts** that anonymous envelopes embed are enumerated: the change-target summary of");
        builder.AppendLine("   every anchor type, and the receipt payload with its optional members absent and present.");
        builder.AppendLine("3. **Response states** run each tool into a named state, and generation fails unless the");
        builder.AppendLine("   response is in that state. Each is recorded as property paths and the JSON kinds seen;");
        builder.AppendLine("   values are omitted because ids, hashes and timestamps vary. An empty array records no");
        builder.AppendLine("   element paths, which is why empty and populated collections are separate states.");

        TypedSchemas(builder, states);
        SharedParts(builder);

        builder.AppendLine();
        builder.AppendLine("### Response states");
        foreach (var group in states.GroupBy(state => state.Tool).OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            builder.AppendLine();
            builder.AppendLine($"#### `{group.Key}`");
            foreach (var state in group)
            {
                builder.AppendLine();
                builder.AppendLine($"State: {state.Name}");
                builder.AppendLine();
                AppendShape(builder, JsonNode.Parse(state.Json));
            }
        }
    }

    private static void TypedSchemas(StringBuilder builder, IReadOnlyList<ResponseStates.State> states)
    {
        builder.AppendLine();
        builder.AppendLine("### Typed results");
        builder.AppendLine();
        builder.AppendLine("A failure these tools report by exception comes back in the error envelope instead, which is");
        builder.AppendLine("frozen among the response states. A member whose schema is `true` has a custom converter; every");
        builder.AppendLine("such member is an anchor, written exactly as the Anchors section above records.");

        foreach (var (tool, type, options) in TypedResponses)
        {
            var schema = Canonical(JsonNode.Parse(AIJsonUtilities.CreateJsonSchema(type, serializerOptions: options).GetRawText()));
            var declared = new HashSet<string>(StringComparer.Ordinal);
            var open = new List<string>();
            SchemaPaths(schema, schema, "$", declared, open, depth: 0);

            // The drift guard: a typed tool that starts returning another type, or a member the
            // schema does not declare, fails here rather than passing with a stale schema.
            foreach (var state in states.Where(state => state.Tool == tool))
            {
                var shape = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
                Shape(JsonNode.Parse(state.Json), "$", shape);
                if (shape.ContainsKey("$.errors") && !declared.Contains("$.errors"))
                    continue; // the error envelope
                var undeclared = shape.Keys.Where(path => !declared.Contains(path) &&
                    !open.Any(prefix => path.StartsWith(prefix, StringComparison.Ordinal))).ToList();
                if (undeclared.Count > 0)
                    throw new InvalidOperationException(
                        $"{tool} / {state.Name} returned paths its {type.Name} schema does not declare: {string.Join(", ", undeclared)}");
            }

            builder.AppendLine();
            builder.AppendLine($"#### `{tool}`");
            builder.AppendLine();
            builder.AppendLine($"Type: `{type.FullName}`");
            builder.AppendLine();
            builder.AppendLine("```json");
            builder.AppendLine(schema?.ToJsonString(new JsonSerializerOptions { WriteIndented = true }).Replace("\r\n", "\n") ?? "null");
            builder.AppendLine("```");
        }
    }

    /// <summary>Every property path a schema declares; subtrees it leaves open are collected apart.</summary>
    private static void SchemaPaths(JsonNode? root, JsonNode? node, string path, HashSet<string> declared, List<string> open, int depth)
    {
        if (node is JsonValue value && value.GetValueKind() == JsonValueKind.True)
        {
            // `true` accepts any value: a member with a custom converter, such as an anchor.
            declared.Add(path);
            open.Add(path);
            return;
        }
        if (node is not JsonObject obj || depth > 40) return;
        declared.Add(path);
        if (obj["$ref"]?.GetValue<string>() is { } reference)
        {
            var target = reference.TrimStart('#').Split('/', StringSplitOptions.RemoveEmptyEntries)
                .Aggregate(root, (current, segment) => current?[segment.Replace("~1", "/").Replace("~0", "~")]);
            SchemaPaths(root, target, path, declared, open, depth + 1);
            return;
        }
        var constrained = false;
        if (obj["properties"] is JsonObject properties)
        {
            constrained = true;
            foreach (var (name, child) in properties)
                SchemaPaths(root, child, $"{path}.{name}", declared, open, depth + 1);
        }
        if (obj["items"] is { } items)
        {
            constrained = true;
            SchemaPaths(root, items, $"{path}[]", declared, open, depth + 1);
        }
        foreach (var keyword in new[] { "anyOf", "oneOf", "allOf" })
            if (obj[keyword] is JsonArray alternatives)
            {
                constrained = true;
                foreach (var alternative in alternatives)
                    SchemaPaths(root, alternative, path, declared, open, depth + 1);
            }
        if (!constrained && obj["type"] is null)
            open.Add(path); // a member with a custom converter: the schema says nothing about its inside
    }

    private static void SharedParts(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("### Shared parts");
        builder.AppendLine();
        builder.AppendLine("Change and error targets are summarised per anchor type. Every concrete anchor type is");
        builder.AppendLine("enumerated from the abstractions assembly, so a new anchor type appears here when it ships.");

        var anchors = typeof(Anchor).Assembly.ExportedTypes
            .Where(type => typeof(Anchor).IsAssignableFrom(type) && !type.IsAbstract && type.GetConstructor(Type.EmptyTypes) is not null)
            .OrderBy(type => type.FullName, StringComparer.Ordinal);
        foreach (var type in anchors)
        {
            builder.AppendLine();
            builder.AppendLine($"Target summary: `{type.Name}`");
            builder.AppendLine();
            AppendShape(builder, JsonNode.Parse(JsonSerializer.Serialize(
                OfficeAgentTools.SummariseAnchor((Anchor)Activator.CreateInstance(type)!), ResponseJson)));
        }

        var minimal = new ApplyReceipt { Outcome = ApplyOutcome.Rejected };
        var full = new ApplyReceipt
        {
            Outcome = ApplyOutcome.Committed,
            PlanSha256 = "plan",
            InputSha256 = "input",
            OutputSha256 = "output",
            TimestampUtc = DateTimeOffset.UnixEpoch,
            Revision = new RevisionMetadata { Author = "Author", TimestampUtc = DateTimeOffset.UnixEpoch },
            Actor = new AuditActor { Subject = "subject", Issuer = "issuer", DisplayName = "name" },
            OutputDocument = new DocumentReference
            {
                Provider = "provider", ConnectionId = "connection", ItemId = "item", Version = "version",
                Name = "name.docx", ContentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            }
        };
        foreach (var (name, receipt) in new[] { ("optional members absent", minimal), ("optional members present", full) })
        {
            builder.AppendLine();
            builder.AppendLine($"Receipt payload: {name}");
            builder.AppendLine();
            AppendShape(builder, JsonNode.Parse(JsonSerializer.Serialize(OfficeAgentTools.ReceiptPayload(receipt), ResponseJson)));
        }
    }

    private static void AppendShape(StringBuilder builder, JsonNode? node)
    {
        var shape = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
        Shape(node, "$", shape);
        builder.AppendLine("```text");
        foreach (var (path, kinds) in shape)
            builder.AppendLine($"{path}: {string.Join(" | ", kinds)}");
        builder.AppendLine("```");
    }

    private static void Shape(JsonNode? node, string path, SortedDictionary<string, SortedSet<string>> shape)
    {
        void Record(string kind)
        {
            if (!shape.TryGetValue(path, out var kinds))
                shape[path] = kinds = new SortedSet<string>(StringComparer.Ordinal);
            kinds.Add(kind);
        }

        switch (node)
        {
            case null:
                Record("null");
                break;
            case JsonObject obj:
                Record("object");
                foreach (var (key, value) in obj)
                    Shape(value, $"{path}.{key}", shape);
                break;
            case JsonArray array:
                Record("array");
                foreach (var item in array)
                    Shape(item, $"{path}[]", shape);
                break;
            case JsonValue value:
                Record(value.GetValueKind() switch
                {
                    JsonValueKind.String => "string",
                    JsonValueKind.Number => "number",
                    JsonValueKind.True or JsonValueKind.False => "boolean",
                    _ => "null"
                });
                break;
        }
    }

    /// <summary>The JSON members of a type as the canonical plan options read and write them.</summary>
    private static IEnumerable<string> Members(Type type)
    {
        var info = PlanJson.GetTypeInfo(type);
        return info.Properties
            .Select(property => $"{property.Name}: {TypeName(property.PropertyType)}" +
                                (property.IsRequired ? " (required)" : ""))
            .OrderBy(text => text, StringComparer.Ordinal);
    }

    private static string TypeName(Type type)
    {
        var nullable = Nullable.GetUnderlyingType(type);
        if (nullable is not null) return TypeName(nullable) + "?";
        if (type.IsArray) return TypeName(type.GetElementType()!) + "[]";
        if (!type.IsGenericType) return type.Name;
        var name = type.Name.Split('`')[0];
        return $"{name}<{string.Join(", ", type.GetGenericArguments().Select(TypeName))}>";
    }

    /// <summary>Sorted keys, descriptions removed, so the text changes only when the contract does.</summary>
    /// <remarks>
    /// Annotations are removed only where they are schema keywords. Inside a <c>properties</c>
    /// map the keys are member names, and a member called <c>title</c> or <c>description</c> is
    /// contract: stripping every such key once dropped <c>DocumentMergeOptions.Title</c>.
    /// </remarks>
    private static JsonNode? Canonical(JsonNode? node, bool memberNames = false)
    {
        switch (node)
        {
            case JsonObject obj:
                var sorted = new JsonObject();
                foreach (var pair in obj.OrderBy(pair => pair.Key, StringComparer.Ordinal))
                {
                    if (!memberNames && pair.Key is "description" or "title") continue;
                    sorted[pair.Key] = Canonical(pair.Value?.DeepClone(),
                        memberNames: !memberNames && pair.Key is "properties" or "$defs" or "definitions");
                }
                return sorted;
            case JsonArray array:
                var copy = new JsonArray();
                foreach (var item in array) copy.Add(Canonical(item?.DeepClone()));
                return copy;
            default:
                return node?.DeepClone();
        }
    }
}
